version: '2'

services:
  db:
    stdin_open: true
    tty: true
    image: postgres:13
    shm_size: '1gb'
    env_file:
      - docker/env/postgres.env
    ports:
      - 5432:5432

  web:
    image: ruby:3
    stdin_open: true
    tty: true
    shm_size: '256mb'
    ports:
      - '3000:3000'
    env_file:
      - docker/env/rails.env
    volumes:
      - .:/app
    depends_on:
      - db
